Web2012023015School/src/Web2012023015School/Models/Activities.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web2012023015School.Models
{
    public class Activities
    {
        //校园活动
        public int Id { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public DateTime Datatime { get; set; }
        public string Content { get; set; }
        public int Priority { get; set; }
    }
}

Web2012023015School/src/Web2012023015School/Models/Article.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web2012023015School.Models
{
    public class Article
    {
        //文章信息(学生，老师写的好的文章
        public int Id { get; set; }
        public string Title { get; set;}
        public DateTime Datatime { get; set; }
        public string Content { get; set; }
        public string Category { get; set; }//文章类别（科幻，悬疑...）
        public string Source { get; set; }
        public string Author { get; set; }
        public int Clickonthequantity{ get; set; }//点击量
        public int Priority { get; set; }//优先级 在推荐中用
    }
}

Web2012023015School/src/Web2012023015School/Models/Inform.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web2012023015School.Models
{
    public class Inform
    {
        //通知公告
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime Datatime { get; set; }
        public string Content { get; set; }
    }
}

Web2012023015School/src/Web2012023015School/Models/News.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web2012023015School.Models
{
    public class News
    {
        //新闻版
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime Datatime { get; set; }
        public string Content { get; set; }
        public int Priority { get; set; }
        public string Source { get; set; }
    }
}

Web2012023015School/src/Web2012023015School/Models/RecruitStudents.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web2012023015School.Models
{
    public class RecruitStudents
    {
        //招生信息
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime Datatime { get; set; }
        public string Content { get; set; }
    }
}

Web2012023015School/src/Web2012023015School/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using Web2012023015School.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Web2012023015School.Controllers
{
    public class PageController : BaseController
    {
        // GET: /<controller>/
        [FromServices]
        public ArticleContext DB { get; set; }
        [HttpGet]
        public IActionResult News()
        {
            var latestnews = DB.News.OrderByDescending(x => x.Datatime).ToList();
            var recommendednews = DB.News.OrderBy(x => x.Priority).ThenByDescending(x => x.Datatime).Take(6).ToList();
            ViewBag.recommendednews = recommendednews;
            return PagedView(latestnews, 7);
        }
     
        [HttpGet]
        public IActionResult Article()
        {
            var article = DB.Article.OrderByDescending(x => x.Datatime).ToList();
            var recommendedarticle = DB.Article.OrderBy(x => x.Priority).ThenByDescending(x => x.Datatime).Take(6).ToList();
            ViewBag.recommendedarticle = recommendedarticle;
            return PagedView(article, 7);
        }
        
        [HttpGet]
        public IActionResult Inform()
        {
            return PagedView(DB.Inform, 7);
        }

        [HttpGet]
        public IActionResult Photos()
        {
            return PagedView(DB.Photos, 7);
        }

        [HttpGet]    
        public IActionResult RecruitStudents()
        {
            var recruit = DB.RecruitStudents.OrderByDescending(x=>x.Datatime).ToList();
            return PagedView(recruit, 10);
        }
        [HttpGet]
        public IActionResult Message()
        {
            var message = DB.Message.OrderByDescending(x => x.Datatime)
                .ToList();
            return PagedView(message,5);
        }

        [HttpGet]
        public IActionResult CEmail()
        {
            return View();
        }
       public IActionResult Activities()
        {
            var activiteis = DB.Activities.OrderByDescending(x => x.Datatime).ToList();
            return PagedView(activiteis, 10);
        }
    }
}

Web2012023015School/src/Web2012023015School/Controllers/ShowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Web2012023015School.Models;

namespace Web2012023015School.Controllers
{
    public class ShowController : BaseController
    {
        [FromServices]
        public ArticleContext DB { get; set; }
        // GET: /<controller>/
        public IActionResult Article(int id)
        {
            var article = DB.Article.Where(x=>x.Id==id).SingleOrDefault();
            return View(article);
        }
        public IActionResult Inform(int id)
        {
            var inform = DB.Inform.Where(x => x.Id == id).SingleOrDefault();
            var others = DB.Inform.Where(x => x.Id != id).OrderByDescending(x => x.Datatime).Take(5).ToList();
            ViewBag.others = others;
            return View(inform);
        }
        public IActionResult News(int id)
        {
            var news = DB.News.Where(x => x.Id == id).SingleOrDefault();
            var latestnews = DB.News.OrderByDescending(x => x.Datatime).Take(6).ToList();
            var hotnews = DB.News.OrderBy(x => x.Id).Take(6).ToList();
            var recommendednews = DB.News.OrderBy(x => x.Priority).ThenByDescending(x=>x.Datatime).Take(6).ToList();
            ViewBag.latestnews = latestnews;
            ViewBag.hotnews = hotnews;
            ViewBag.recommendednews = recommendednews;
            return View(news);
        }
        public IActionResult Photes()
        {
            return View();
        }
        public IActionResult RecruitStudents(int id)
        {
            var recruit = DB.RecruitStudents.Where(x => x.Id == id).SingleOrDefault();
            var others = DB.RecruitStudents.Where(x => x.Id != id).OrderByDescending(x => x.Datatime).Take(5).ToList();
            ViewBag.others = others;
            return View(recruit);
        }
        public IActionResult Activities(int id)
        {
            var activities = DB.Activities.Where(x => x.Id == id).SingleOrDefault();
            var others = DB.Activities.Where(x => x.Id != id).OrderByDescending(x => x.Datatime).Take(5).ToList();
            ViewBag.others = others;
            return View(activities);
        }
    }
}

Web2012023015School/src/Web2012023015School/Views/Show/Activities.cshtml
@{
    Layout = "~/Views/Shared/_Display.cshtml";
}
<link rel="stylesheet" href="~/styles/new.css" />
@model Activities
<div class="activities">
    <div style="height:20px;color:#eee;margin-top:-20px;"></div>
    <div class="container">
        <div class="col-md-8 page-content" style="box-shadow:3px 3px 3px #ccc;">
            <div class="panel-heading">
                <h3 style="text-align:center;">@Model.Title</h3>
                <p class="text-muted"><small>发布时间：@Model.Datatime</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<small>举办地点：@Model.Address </small> <small class="pull-right">浏览量：<span>9999+</span></small></p>
            </div>
            <div class="panel-body">
                <p>@Model.Content</p>
            </div>
        </div>

        <div class="col-md-4" style="margin-top:10px;">
            <div class="panel panel-default" style="box-shadow:3px 3px 3px 8px #cfc;">
                <div class="panel-heading" style="background-color:rgb(250,96,96);">
                    <h3 class="panel-title" style="color:rgb(255,255,255);">其它通知</h3>
                </div>
                @foreach (Activities others in ViewBag.others)
            {
                    <div class="panel-body">
                        <a asp-action="Activities" asp-controller="Show" asp-route-id="@others.Id" style="text-decoration:none;">@others.Title</a><small class="pull-right text-muted"></small>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Web2012023015School/src/Web2012023015School/Views/Show/Article.cshtml
@{
    Layout = "~/Views/Shared/_Display.cshtml";
}
<link rel="stylesheet" type="text/css" href="~/styles/new.css" />
@model Article
<div style="margin-top:-20px;"></div>
<div class="page">
    <div class="container">
        <div class="col-md-8 page-content" style="box-shadow:3px 3px 3px #ccc;">
            <div class="panel-heading">
                <h3 style="text-align:center;">@Model.Title</h3>
                <p class="text-muted"><small>发布时间：@Model.Datatime</small> &nbsp;&nbsp;&nbsp;<small class="pull-right">浏览量：<span>9999+</span></small></p>
            </div>
            <div class="panel-body">
                <p>@Model.Content</p>
            </div>
        </div>
        @*<div class="col-md-4">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#latestnews" data-toggle="tab">最新新闻</a>
                </li>
                <li>
                    <a href="#hotnews" data-toggle="tab">热点新闻</a>
                </li>
                <li>
                    <a href="#recommendednews" data-toggle="tab">推荐新闻</a>
                </li>
                <li>
                    <a asp-action="News" asp-controller="Page" class="pull-right">更多</a>
                </li>
            </ul>
            <div class="panel">
                <div class="panel-body">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="latestnews">
                            @foreach (News latesnews in ViewBag.latestnews)
                            {
                                <a asp-action="News" asp-controller="Show" asp-route-id="@latesnews.Id"><p>@latesnews.Title</p></a>
                            }
                        </div>
                        <div class="tab-pane fade" id="hotnews">
                            @foreach (News hotnews in ViewBag.hotnews)
            {
                                <a asp-action="News" asp-controller="Show" asp-route-id="@hotnews.Id"><p>@hotnews.Title</p></a>
                            }
                        </div>
                        <div class="tab-pane fade" id="recommendednews">
                            @foreach (News recommendednews in ViewBag.recommendednews)
            {
                                <a asp-action="News" asp-controller="Show" asp-route-id="@recommendednews.Id"><p>@recommendednews.Title</p></a>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>*@
    </div>
</div>
<div style="height:20px;background-color:#eee;"></div>

Web2012023015School/src/Web2012023015School/Views/Show/Inform.cshtml
@{
    Layout = "~/Views/Shared/_Display.cshtml";
}
<link rel="stylesheet" href="~/styles/new.css" />
@model Inform
<div class="inform">
    <div style="height:20px;color:#eee;margin-top:-20px;"></div>
    <div class="container">
        <div class="col-md-8 page-content" style="box-shadow:3px 3px 3px #ccc;">
            <div class="panel-heading">
                <h3 style="text-align:center;">@Model.Title</h3>
                <p class="text-muted"><small>发布时间：@Model.Datatime</small> &nbsp;&nbsp;&nbsp;<small class="pull-right">浏览量：<span>9999+</span></small></p>
            </div>
            <div class="panel-body">
                <p>@Model.Content</p>
            </div>
        </div>

        <div class="col-md-4" style="margin-top:10px;">
            <div class="panel panel-default" style="box-shadow:3px 3px 3px 8px #cfc;">
                <div class="panel-heading" style="background-color:rgb(250,96,96);">
                    <h3 class="panel-title" style="color:rgb(255,255,255);">其它通知</h3>
                </div>
                @foreach (Inform others in ViewBag.others)
            {
                    <div class="panel-body">
                        <a asp-action="Inform" asp-controller="Show" asp-route-id="@others.Id" style="text-decoration:none;">@others.Title</a><small class="pull-right text-muted"></small>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Web2012023015School/src/Web2012023015School/Views/Show/News.cshtml
@{
    Layout = "~/Views/Shared/_Display.cshtml";
}
<link rel="stylesheet" type="text/css" href="~/styles/new.css"/>
@model News
<div style="margin-top:-20px"></div>
<div class="page">
    <div class="container">
        <div class="col-md-8 page-content" style="box-shadow:3px 3px 3px #ccc;">
                <div class="panel-heading">
                    <h4 style="text-align:center;">@Model.Title</h4>
                    <p class="text-muted"><small>发布时间：@Model.Datatime</small> &nbsp;&nbsp;&nbsp;<small class="pull-right">浏览量：<span>9999+</span></small></p>
                </div>
                <div class="panel-body">
                    <p>@Model.Content</p>
                </div>
        </div>
        <div class="col-md-4">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#latestnews" data-toggle="tab">最新新闻</a>
                </li>
                <li>
                    <a href="#hotnews" data-toggle="tab">热点新闻</a>
                </li>
                <li>
                    <a href="#recommendednews" data-toggle="tab">推荐新闻</a>
                </li>
                <li>
                    <a asp-action="News" asp-controller="Page" class="pull-right">更多</a>
                </li>
            </ul>
            <div class="panel">
                <div class="panel-body">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="latestnews">
                                                        @foreach (News latesnews in ViewBag.latestnews)
                                                        {
                                                            <p><a asp-action="News" asp-controller="Show" asp-route-id="@latesnews.Id">@latesnews.Title</a><small class="pull-right text-muted">@latesnews.Datatime</small></p>
                                                        }
                        </div>
                        <div class="tab-pane fade" id="hotnews">
                            @foreach (News hotnews in ViewBag.hotnews)
            {
                                <p><a asp-action="News" asp-controller="Show" asp-route-id="@hotnews.Id">@hotnews.Title</a><small class="pull-right text-muted">@hotnews.Datatime</small></p>
                            }
                        </div>
                        <div class="tab-pane fade" id="recommendednews">
                            @foreach (News recommendednews in ViewBag.recommendednews)
            {
                                <p><a asp-action="News" asp-controller="Show" asp-route-id="@recommendednews.Id">@recommendednews.Title</a><small class="pull-right text-muted">@recommendednews.Datatime</small></p>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web2012023015School/src/Web2012023015School/Views/Show/RecruitStudents.cshtml
@{
    Layout = "~/Views/Shared/_Display.cshtml";
}
<link rel="stylesheet" href="~/styles/new.css" />
@model RecruitStudents
<div class="recruit">
    <div style="height:20px;color:#eee;margin-top:-20px;"></div>
    <div class="container">
        <div class="col-md-8 page-content" style="box-shadow:3px 3px 3px #ccc;">
            <div class="panel-heading">
                <h3 style="text-align:center;">@Model.Title</h3>
                <p class="text-muted"><small>发布时间：@Model.Datatime</small> &nbsp;&nbsp;&nbsp;<small class="pull-right">浏览量：<span>9999+</span></small></p>
            </div>
            <div class="panel-body">
                <p>@Model.Content</p>
            </div>
        </div>

        <div class="col-md-4" style="margin-top:10px;">
            <div class="panel panel-default" style="box-shadow:3px 3px 3px 8px #cfc;">
                <div class="panel-heading" style="background-color:rgb(250,96,96);">
                    <h3 class="panel-title" style="color:rgb(255,255,255);">其它招生信息</h3>
                </div>
                @foreach (RecruitStudents others in ViewBag.others)
            {
                    <div class="panel-body">
                        <a asp-action="RecruitStudents" asp-controller="Show" asp-route-id="@others.Id" style="text-decoration:none;">@others.Title</a><small class="pull-right text-muted"></small>
                    </div>
                }
            </div>
        </div>
    </div>
</div>